apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-backend
  template:
    metadata:
      labels:
        app: innovatech-backend
      annotations:
        rollme: "DUMMY"
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: 846244128735.dkr.ecr.eu-central-1.amazonaws.com/innovatech-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              value: eu-central-1
            - name: EMPLOYEE_TABLE
              value: innovatech-employees
            - name: AUDIT_TABLE
              value: innovatech-audit-logs
            - name: COGNITO_POOL_ID
              value: eu-central-1_BEC7JQwYd
            - name: COGNITO_CLIENT_ID
              value: 68nlqmca9tb48urul3fpvu58e
