apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-backend
  labels:
    app: innovatech-backend
spec:
  replicas: 1

  # RECREATE
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: innovatech-backend

  template:
    metadata:
      labels:
        app: innovatech-backend
      annotations:
        rollme: "DUMMY"

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/innovatech-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          env:
            - name: AWS_REGION
              value: <AWS_REGION>
            - name: EMPLOYEE_TABLE
              value: innovatech-employees
            - name: AUDIT_TABLE
              value: innovatech-audit-logs
            - name: COGNITO_POOL_ID
              value: <COGNITO_POOL_ID>
            - name: COGNITO_CLIENT_ID
              value: <COGNITO_CLIENT_ID>
            - name: WORKSTATION_LT_ID
              value: <WORKSTATION_LT_ID>
            - name: WORKSTATION_SUBNET_ID
              value: <WORKSTATION_SUBNET_ID>

          # PROBES 
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
