apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:846244128735:certificate/68497f6d-e031-4660-9795-da723467053a
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: innovatech

    # --- Cognito Auth ---
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-session-timeout: "604800"
    alb.ingress.kubernetes.io/auth-idp-cognito: >
      {"UserPoolArn":"arn:aws:cognito-idp:eu-central-1:846244128735:userpool/eu-central-1_BEC7JQwYd",
       "UserPoolClientId":"68nlqmca9tb48urul3fpvu58e",
       "UserPoolDomain":"innovatech-b37ae2b2"}
spec:
  rules:
  - host: portal.daanwelten.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80